version: '3.8'

services:
  dev:
    image: ghcr.io/KaruroChori/vs-fltk:build-env
    container_name: vs-fltk-env
    volumes:
      - ${PWD}:/workspace
    working_dir: /workspace
    command: >
      bash -l -c "
        bun install &&
        bun run codegen &&
        bun run meson-setup.clang-release &&
        meson compile -C build/ vs:executable
      "
    environment:
      HOSTUID: $HOSTUID
      HOSTUID: $HOSTGID
    stdin_open: true # Allows interactive mode
    tty: true # Allocate a pseudo-TTY
