name: Test Build-Env Docker Image

on:
  pull_request:
    branches: master
    paths:
    - '**Dockerfile'
    - '**docker.yml'

jobs:
  build-test-env-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: docker build -t test-image -f docker/Dockerfile .

    - name: Build Docker image
      run: docker build -t test-image -f docker/Dockerfile docker

    - name: Run commands in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace \
          -e HOSTUID=$(id -u) -e HOSTGID=$(id -g) test-image \
          '/bin/bash -l -c "
          cd /workspace &&
            bun install &&
            bun run codegen &&
            bun run meson-setup.clang-release &&
            meson compile -C build/ vs:executable
          "'
  
