name: Build-Env Docker Image

on:
  push:
    branches: master
    paths:
    - '**Dockerfile'
    - '**docker.yml'
  pull_request:
    branches: master
    paths:
    - '**Dockerfile'
    - '**docker.yml'
  workflow_dispatch:
  schedule:
    - cron: '25 1 5 * *'

jobs:
  build-env-image:
    runs-on: ubuntu-24.04
    env:
      REGISTRY_IMAGE: ghcr.io/karurochori/vs-fltk
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: karurochori
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ./docker/Dockerfile
          context: ./docker
          push: true
          tags: ${{ env.REGISTRY_IMAGE }}:test
          cache-from: type=registry,ref=${{ env.REGISTRY_IMAGE }}:build-env-buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_IMAGE }}:build-env-buildcache,mode=max
