name: Release
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-release
  cancel-in-progress: true

on:
  push:
    tags:
      - "v**"
    branches: [master]
jobs:
  build-checks:
    uses: ./.github/workflows/build.yml
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
  release:
    needs: [build-checks]
    name: release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    steps:
      - run: exit 0
      #TODO https://github.com/quickjs-ng/quickjs/blob/master/.github/workflows/release.yml or https://github.com/saghul/txiki.js/blob/master/.github/workflows/release.yml for reference?
